name: covid_dashboard
description: A Covid Dashboard made in Flutter â¤

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.5

  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/ios-icon.png'
  adaptive_icon_background: '#161E2C'
  adaptive_icon_foreground: 'assets/adaptive-icon.png'
  android: true
  ios: true

flutter:
  uses-material-design: true
